# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Roguelike' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Roguelike

  target 'RoguelikeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RoguelikeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
